version: "3.7"
services:
  nginx-lumen:
    build: images/nginx-lumen
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "9090:80"
    volumes:
      - ./images/php/lumen:/var/www/html/lumen
    # networks:
    #   - laravel

  nginx-laravel:
    build: images/nginx-laravel
    command: nginx -g "daemon off;"
    links:
      - php
      - nginx-lumen
    ports:
      - "8080:80"
    volumes:
      - ./images/php/laravel:/var/www/html/laravel
    # networks:
    #   - laravel

  php:
    build: images/php
    volumes:
      - ./images/php/lumen:/var/www/html/lumen
      - ./images/php/laravel:/var/www/html/laravel
    working_dir: /var/www/html/lumen/public
    command: php-fpm
    links:
      - db
      - cache
    ports:
      - "9000:9000"
    environment:
      APP_ENV: local
      API_URL: nginx-lumen
      APP_DEBUG: 'true'
      APP_KEY: 'base64:tobCDR2OO1txlMs+aQXYUALNb6AQJbUXBEow9tCnH3Y='
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    # networks:
    #   - laravel

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password # needed as of mysql 8
    ports:
      - "3307:3307"
    volumes:
        - ./images/mysql/init:/docker-entrypoint-initdb.d
        #- database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # networks:
    #   - laravel
    
  cache:
    image: memcached:1.6-alpine
  
networks:
  laravel:
    driver: bridge